server:
  port: 8080
spring:
  application:
    name: oauth2-server
  datasource:
    url: jdbc:mysql://192.168.0.10:3306/oath?useSSL=false
    username: root
    password: qwe123
    driver-class-name: com.mysql.cj.jdbc.Driver
